version: 0.1.{build}

image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master

build:
  verbosity: minimal
  parallel: true
  project: AutoSplat.sln
  publish_nuget: false
  publish_nuget_symbols: false
  include_nuget_references: true

before_build:
  - nuget restore AutoSplat.sln

dotnet_csproj:
  patch: true
  file: 'AutoSplat\AutoSplat.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'