version: 1.0.{build}

image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master

build:
  verbosity: minimal
  parallel: true
  project: AutoSplat.sln
  publish_nuget: false
  publish_nuget_symbols: false

before_build:
  - nuget restore AutoSplat.sln

dotnet_csproj:
  patch: true
  file: 'AutoSplat\AutoSplat.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

artifacts:
  - path: '**\*.nupkg'
    name: Packages

deploy:
  provider: NuGet
  api_key:
    secure: BKFZiNBzxIo7iznqfjlIy85yPtwk5pgHpf2YguGaRVsNdIFOMSoCdD0K0mD4SuVT
  skip_symbols: true