pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - script: dotnet restore
    displayName: 'Restoring Packages'

  - script: dotnet build --configuration Debug --version-suffix $(Build.BuildNumber)
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/release')
    displayName: 'Building'

  - script: dotnet test --logger trx
    displayName: 'Run automated tests'
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      failOnStandardError: 'true'

  - script: dotnet build --configuration Release
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/release')
    displayName: 'Building (Release)'

  - task: NuGetCommand@2
    displayName: 'Publishing Build'
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/release')))
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: 'AutoSplat.NuGet'
      packagesToPush: './Artifacts/**/*.nupkg'